#!/bin/sh
#
# STIG URL: http://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2014-06-11/finding/V-38631
# Finding ID:	V-38631
# Version:	RHEL-06-000148
# Finding Level:	Medium
#
#     The operating system must employ automated mechanisms to facilitate 
#     the monitoring and control of remote access methods. Ensuring the 
#     "auditd" service is active ensures audit records generated by the 
#     kernel can be written to disk, or that appropriate actions will be 
#     taken if other obstacles exist.
#
############################################################

diag_out() {
   echo "${1}"
}

diag_out "----------------------------------"
diag_out "STIG Finding ID: V-38631"
diag_out "  system must employ automated"
diag_out "  mechanisms to facilitate the"
diag_out "  monitoring and control of"
diag_out "  remote access methods"
diag_out "----------------------------------"
