#!/bin/sh
#
# STIG URL: http://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2014-06-11/finding/V-38519
# Finding ID:	V-38519
# Version:	RHEL-06-000134
# Finding Level:	Medium
#
#     All rsyslog-generated log files must be group-owned by root. The log 
#     files generated by rsyslog contain valuable information regarding 
#     system configuration, user authentication, and other such 
#     information. Log files should be protected from unauthorized access.
#
############################################################

diag_out() {
   echo "${1}"
}

diag_out "----------------------------------"
diag_out "STIG Finding ID: V-38519"
diag_out "  All rsyslog-generated log files"
diag_out "  must be group-owned by root"
diag_out "----------------------------------"
