include:
  - ash-linux.el9.RuleById.high.content_rule_grub2_uefi_password
  - ash-linux.el9.RuleById.medium.content_rule_mount_option_tmp_noexec
  - ash-linux.el9.RuleById.medium.content_rule_rsyslog_remote_loghost
  - ash-linux.el9.RuleById.medium.content_rule_configure_tmux_lock_after_time
  - ash-linux.el9.RuleById.medium.content_rule_configure_bashrc_exec_tmux
  - ash-linux.el9.RuleById.medium.content_rule_configure_tmux_lock_command
  - ash-linux.el9.RuleById.medium.content_rule_chronyd_server_directive
  - ash-linux.el9.RuleById.medium.content_rule_sudo_remove_nopasswd
  - ash-linux.el9.RuleById.medium.content_rule_postfix_client_configure_mail_alias
  - ash-linux.el9.RuleById.medium.content_rule_firewalld_sshd_port_enabled
  - ash-linux.el9.RuleById.medium.content_rule_network_configure_name_resolution
  - ash-linux.el9.RuleById.low.content_rule_configure_usbguard_auditbackend
  - ash-linux.el9.RuleById.low.content_rule_no_tmux_in_shells
