#!/bin/sh
#
# STIG URL: http://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2014-06-11/finding/V-38518
# Finding ID:	V-38518
# Version:	
# Finding Level:	Medium
#
#     All rsyslog-generated log files must be owned by root. The log files 
#     generated by rsyslog contain valuable information regarding system 
#     configuration, user authentication, and other such information. Log 
#     files should be protected from unauthorized access.
#
############################################################

