#!/bin/sh
#
# STIG URL: http://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2014-06-11/finding/V-38632
# Finding ID:	V-38632
# Version:	
# Finding Level:	Medium
#
#     The operating system must produce audit records containing sufficient 
#     information to establish what type of events occurred. Ensuring the 
#     "auditd" service is active ensures audit records generated by the 
#     kernel can be written to disk, or that appropriate actions will be 
#     taken if other obstacles exist.
#
############################################################

